// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: financial_type.sql

package db

import (
	"context"
)

const getFinancialByName = `-- name: GetFinancialByName :one
SELECT id, type FROM financial_types
WHERE type = $1
`

func (q *Queries) GetFinancialByName(ctx context.Context, type_ string) (FinancialType, error) {
	row := q.db.QueryRow(ctx, getFinancialByName, type_)
	var i FinancialType
	err := row.Scan(&i.ID, &i.Type)
	return i, err
}
