// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Financial struct {
	ID        int64              `json:"id"`
	UserID    string             `json:"user_id"`
	Amount    int64              `json:"amount"`
	Direction string             `json:"direction"`
	TypeID    int64              `json:"type_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type FinancialType struct {
	ID   int64  `json:"id"`
	Type string `json:"type"`
}

type User struct {
	Username  string             `json:"username"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Phone     string             `json:"phone"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
