// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Budget struct {
	ID        int32          `json:"id"`
	UserID    string         `json:"user_id"`
	Month     int32          `json:"month"`
	Year      int32          `json:"year"`
	Amount    pgtype.Numeric `json:"amount"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Financial struct {
	ID        int64     `json:"id"`
	UserID    string    `json:"user_id"`
	Amount    int64     `json:"amount"`
	Direction string    `json:"direction"`
	TypeID    int64     `json:"type_id"`
	CreatedAt time.Time `json:"created_at"`
}

type FinancialType struct {
	ID   int64  `json:"id"`
	Type string `json:"type"`
}

type User struct {
	Username  string    `json:"username"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Phone     string    `json:"phone"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
