// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFinancial(ctx context.Context, id int64) (Financial, error)
	GetFinancialById(ctx context.Context, id int64) (GetFinancialByIdRow, error)
	GetFinancialByName(ctx context.Context, type_ string) (FinancialType, error)
	GetFinancialOwner(ctx context.Context, id int64) (string, error)
	GetUser(ctx context.Context, username string) (User, error)
	InsertNewFinancial(ctx context.Context, arg InsertNewFinancialParams) (Financial, error)
	LoginUser(ctx context.Context, username string) (LoginUserRow, error)
	MyFinancial(ctx context.Context, userID string) ([]MyFinancialRow, error)
	UpdateFinancial(ctx context.Context, arg UpdateFinancialParams) (Financial, error)
}

var _ Querier = (*Queries)(nil)
